theme: minima
title: Honeys and BeeBees: A Kitties' Story
author: Paco Kitties
description: Where a paco kitties writes as if he is kitties about Dude and Tuna Dude, who is mostly, little bit kitties' sometimes not so much
